### ISSUE TITLE
Add count of multiple winners

### ISSUE THREAD

**Issue by louis-88** [snackaholic/hivefortune#5]
If enabled "Multiple Winners" a Count behind the Name how often the Winner won would be great.

**Comment by snackaholic** [comment]
fixed in af22e0cc054e46921bb12fb00b440afbc6a637ab

old:

![old-winning](https://user-images.githubusercontent.com/36051495/202781465-1e346b66-9d43-437e-96af-a992fc1660d2.png)



new:


![new-winning](https://user-images.githubusercontent.com/36051495/202781461-35b3a534-598b-4b4d-8944-a882cd9d1409.png)
